import type { RoomPermission } from './roomTypes';

/** Fallback hors-ligne — aligné migration 077 */
export const DEFAULT_ROOM_PERMISSIONS: Omit<RoomPermission, 'id' | 'created_at' | 'updated_at'>[] = [
  { room_key: 'wall', room_name: 'Mur société', description: null, category: 'Communauté', icon: 'MessageSquare', color: '#3b82f6', route: '/wall', sort_order: 10, enabled: true, visible_to_roles: ['visiteur', 'chauffeur', 'admin'], admin_critical: false },
  { room_key: 'profile', room_name: 'Profil', description: null, category: 'Compte', icon: 'User', color: '#8b5cf6', route: '/profile', sort_order: 10, enabled: true, visible_to_roles: ['visiteur', 'chauffeur', 'admin'], admin_critical: true },
  { room_key: 'settings', room_name: 'Paramètres', description: null, category: 'Compte', icon: 'Settings', color: '#64748b', route: '/settings', sort_order: 20, enabled: true, visible_to_roles: ['visiteur', 'chauffeur', 'admin'], admin_critical: true },
  { room_key: 'updates', room_name: 'À propos', description: null, category: 'Communauté', icon: 'Bell', color: '#06b6d4', route: '/updates', sort_order: 20, enabled: true, visible_to_roles: ['visiteur', 'chauffeur', 'admin'], admin_critical: false },
  { room_key: 'dashboard', room_name: 'Tableau de bord', description: null, category: 'ERP', icon: 'LayoutDashboard', color: '#ef4444', route: '/dashboard', sort_order: 10, enabled: true, visible_to_roles: ['visiteur', 'chauffeur', 'admin'], admin_critical: false },
  { room_key: 'driver_portal', room_name: 'Portail chauffeur', description: null, category: 'ERP', icon: 'Smartphone', color: '#f97316', route: '/driver', sort_order: 220, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'freight_market', room_name: 'Marché Fret', description: null, category: 'ERP', icon: 'Container', color: '#f97316', route: '/freight', sort_order: 60, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'clovis_rental', room_name: 'Location Clovis', description: 'Agence location Renault T — 450 €/jour', category: 'ERP', icon: 'KeyRound', color: '#f59e0b', route: '/clovis-rental', sort_order: 55, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'road_sheets', room_name: 'Feuilles de route', description: null, category: 'ERP', icon: 'Route', color: '#f97316', route: '/road-sheets', sort_order: 110, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'dispatch', room_name: 'Dispatch', description: null, category: 'ERP', icon: 'Radio', color: '#f97316', route: '/dispatch', sort_order: 50, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'gps_tracking', room_name: 'GPS Tracking', description: null, category: 'ERP', icon: 'Map', color: '#f97316', route: '/tracking', sort_order: 70, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'fleet_map', room_name: 'Carte flotte', description: null, category: 'ERP', icon: 'Map', color: '#f97316', route: '/fleet-map', sort_order: 80, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'documents', room_name: 'Dossier chauffeur', description: null, category: 'ERP', icon: 'Archive', color: '#f97316', route: '/documents', sort_order: 210, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'driver_integrations', room_name: 'Mes intégrations', description: null, category: 'Compte', icon: 'Plug', color: '#f97316', route: '/integrations', sort_order: 15, enabled: true, visible_to_roles: ['chauffeur', 'admin'], admin_critical: false },
  { room_key: 'drivers', room_name: 'Gestion chauffeurs', description: null, category: 'ERP', icon: 'Users', color: '#eab308', route: '/drivers', sort_order: 20, enabled: true, visible_to_roles: ['admin'], admin_critical: false },
  { room_key: 'fleet', room_name: 'Flotte', description: null, category: 'ERP', icon: 'Truck', color: '#eab308', route: '/fleet', sort_order: 30, enabled: true, visible_to_roles: ['admin'], admin_critical: false },
  { room_key: 'garages', room_name: 'Garages', description: null, category: 'ERP', icon: 'Building2', color: '#eab308', route: '/garages', sort_order: 40, enabled: true, visible_to_roles: ['admin'], admin_critical: false },
  { room_key: 'finance', room_name: 'Finance', description: null, category: 'ERP', icon: 'BarChart3', color: '#eab308', route: '/finance', sort_order: 120, enabled: true, visible_to_roles: ['admin'], admin_critical: false },
  { room_key: 'bank', room_name: 'Banque entreprise', description: null, category: 'ERP', icon: 'Banknote', color: '#eab308', route: '/bank', sort_order: 160, enabled: true, visible_to_roles: ['admin'], admin_critical: false },
  { room_key: 'administration', room_name: 'Administration', description: null, category: 'Administration', icon: 'Shield', color: '#eab308', route: '/administration', sort_order: 10, enabled: true, visible_to_roles: ['admin'], admin_critical: true },
  { room_key: 'roles_salons', room_name: 'Rôles et salons', description: null, category: 'Administration', icon: 'KeyRound', color: '#eab308', route: '/administration/roles-salons', sort_order: 15, enabled: true, visible_to_roles: ['admin'], admin_critical: true },
  { room_key: 'recruitment', room_name: 'Recrutement', description: null, category: 'Recrutement', icon: 'Briefcase', color: '#3b82f6', route: '/recruitment', sort_order: 10, enabled: true, visible_to_roles: ['visiteur', 'admin'], admin_critical: false },
  { room_key: 'recruitment_applications', room_name: 'Mes candidatures', description: null, category: 'Recrutement', icon: 'FileText', color: '#3b82f6', route: '/recruitment/applications', sort_order: 20, enabled: true, visible_to_roles: ['visiteur'], admin_critical: false },
];
