import type { PostgrestError } from '@supabase/supabase-js';
import { supabase, type Transaction } from './supabase';

export const TRANSACTION_COLUMNS_MINIMAL =
  'id,user_id,type,amount,description,category,date,created_at';

export const TRANSACTION_COLUMNS_EXTENDED =
  `${TRANSACTION_COLUMNS_MINIMAL},driver_id,road_sheet_id,truck_id,garage_id,auto_generated,created_by,reference,balance_after,status,source,metadata`;

export const TRANSACTION_COLUMNS_BALANCE = 'type,amount,status';

export function logSupabaseError(context: string, error: PostgrestError | null | undefined): void {
  if (!error) return;
  console.error(`[Z&D] ${context}:`, {
    message: error.message,
    code: error.code,
    details: error.details,
    hint: error.hint,
  });
}

export function isMissingColumnError(error: PostgrestError | null | undefined): boolean {
  if (!error) return false;
  const msg = error.message?.toLowerCase() ?? '';
  return (
    error.code === 'PGRST204' ||
    msg.includes('schema cache') ||
    msg.includes('could not find') ||
    (msg.includes('column') && msg.includes('does not exist'))
  );
}

export interface FetchTransactionsOptions {
  orderBy?: 'date' | 'created_at';
  ascending?: boolean;
  limit?: number;
  dateFrom?: string;
  dateTo?: string;
  category?: string;
}

export async function fetchAllTransactions(
  options: FetchTransactionsOptions = {},
): Promise<Transaction[]> {
  const orderBy = options.orderBy ?? 'date';
  const ascending = options.ascending ?? false;

  const runQuery = (columns: string) => {
    let query = supabase.from('transactions').select(columns).order(orderBy, { ascending });
    if (options.limit) query = query.limit(options.limit);
    if (options.dateFrom) query = query.gte('date', options.dateFrom);
    if (options.dateTo) query = query.lte('date', options.dateTo);
    if (options.category && options.category !== 'all') {
      query = query.eq('category', options.category);
    }
    return query;
  };

  let { data, error } = await runQuery(TRANSACTION_COLUMNS_EXTENDED);
  if (error && isMissingColumnError(error)) {
    logSupabaseError('fetchAllTransactions fallback minimal columns', error);
    ({ data, error } = await runQuery(TRANSACTION_COLUMNS_MINIMAL));
  }

  if (error) {
    logSupabaseError('fetchAllTransactions failed', error);
    throw error;
  }

  return (data ?? []) as unknown as Transaction[];
}

export async function fetchTransactionById(id: string): Promise<Transaction | null> {
  let { data, error } = await supabase
    .from('transactions')
    .select(TRANSACTION_COLUMNS_EXTENDED)
    .eq('id', id)
    .maybeSingle();

  if (error && isMissingColumnError(error)) {
    logSupabaseError('fetchTransactionById fallback minimal columns', error);
    ({ data, error } = await supabase
      .from('transactions')
      .select(TRANSACTION_COLUMNS_MINIMAL)
      .eq('id', id)
      .maybeSingle());
  }

  if (error) {
    logSupabaseError('fetchTransactionById failed', error);
    throw error;
  }

  return (data as Transaction | null) ?? null;
}

export async function fetchLatestTransactionForUser(userId: string): Promise<Transaction | null> {
  let { data, error } = await supabase
    .from('transactions')
    .select(TRANSACTION_COLUMNS_EXTENDED)
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error && isMissingColumnError(error)) {
    logSupabaseError('fetchLatestTransactionForUser fallback minimal columns', error);
    ({ data, error } = await supabase
      .from('transactions')
      .select(TRANSACTION_COLUMNS_MINIMAL)
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle());
  }

  if (error) {
    logSupabaseError('fetchLatestTransactionForUser failed', error);
    throw error;
  }

  return (data as Transaction | null) ?? null;
}

export async function fetchTransactionAmountsForBalance(): Promise<
  Array<{ type: string; amount: number; status?: string | null }>
> {
  let { data, error } = await supabase.from('transactions').select(TRANSACTION_COLUMNS_BALANCE);

  if (error && isMissingColumnError(error)) {
    logSupabaseError('fetchTransactionAmountsForBalance fallback type,amount', error);
    ({ data, error } = await supabase.from('transactions').select('type,amount'));
  }

  if (error) {
    logSupabaseError('fetchTransactionAmountsForBalance failed', error);
    throw error;
  }

  return (data ?? []) as Array<{ type: string; amount: number; status?: string | null }>;
}

function roadSheetReferencePrefix(roadSheetId: string): string {
  return `RS-${roadSheetId.slice(0, 8)}`;
}

function isAutoGeneratedRoadSheetRow(row: {
  road_sheet_id?: string | null;
  reference?: string | null;
  description?: string | null;
}): boolean {
  const ref = String(row.reference ?? '');
  const desc = String(row.description ?? '');
  return ref.startsWith('RS-') || desc.includes('Feuille de route') || desc.includes('Livraison ');
}

export async function fetchSyncedRoadSheetIds(): Promise<Set<string>> {
  const extended = await supabase
    .from('transactions')
    .select('road_sheet_id,reference,description,auto_generated')
    .not('road_sheet_id', 'is', null);

  if (!extended.error) {
    return new Set(
      (extended.data ?? [])
        .filter(row => row.road_sheet_id && (row.auto_generated === true || isAutoGeneratedRoadSheetRow(row)))
        .map(row => row.road_sheet_id as string),
    );
  }

  if (!isMissingColumnError(extended.error)) {
    logSupabaseError('fetchSyncedRoadSheetIds extended', extended.error);
  }

  const byReference = await supabase
    .from('transactions')
    .select('road_sheet_id,reference,description')
    .like('reference', 'RS-%');

  if (!byReference.error) {
    return new Set(
      (byReference.data ?? [])
        .map(row => row.road_sheet_id as string | null)
        .filter((id): id is string => !!id),
    );
  }

  if (!isMissingColumnError(byReference.error)) {
    logSupabaseError('fetchSyncedRoadSheetIds reference fallback', byReference.error);
  }

  return new Set();
}

export async function fetchExistingRoadSheetTransactionTypes(
  roadSheetId: string,
): Promise<Set<string>> {
  const bySheet = await supabase
    .from('transactions')
    .select('type')
    .eq('road_sheet_id', roadSheetId);

  if (!bySheet.error) {
    return new Set((bySheet.data ?? []).map(row => row.type as string));
  }

  if (!isMissingColumnError(bySheet.error)) {
    logSupabaseError('fetchExistingRoadSheetTransactionTypes by road_sheet_id', bySheet.error);
  }

  const ref = roadSheetReferencePrefix(roadSheetId);
  const byRef = await supabase.from('transactions').select('type').eq('reference', ref);

  if (!byRef.error) {
    return new Set((byRef.data ?? []).map(row => row.type as string));
  }

  logSupabaseError('fetchExistingRoadSheetTransactionTypes by reference', byRef.error);
  return new Set();
}
